---
#
# playbook: provision
#

# role: commons

app_name: myapp
timezone: UTC
locale: en_US.UTF-8
swap_enabled: yes
swap_file_path: /swapfile
swap_file_size_kb: 1024

# role:  deploy-user

deploy_user: deploy
deploy_group: "{{ deploy_user }}"
deploy_user_path: "/home/{{ deploy_user }}"
authorized_public_keys: []

# role: ruby

rbenv_version: master
ruby_install_version: 0.6.0
ruby_version: 2.3.3

rbenv_repo: "git://github.com/sstephenson/rbenv.git"
rbenv_root_path: "{{ deploy_user_path }}/.rbenv"
rubies_path: "{{ rbenv_root_path }}/versions"
ruby_path: "{{ rubies_path }}/{{ ruby_version }}"

local_ruby_path: "~/.rbenv/versions/{{ ruby_version }}"

rbenv_bin: "{{ rbenv_root_path }}/bin/rbenv"
bundle: "{{ rbenv_root_path }}/shims/bundle"

# role: nodejs

nodesource_url: https://deb.nodesource.com/setup_6.x

#
# playbook: deploy
#

git_url: "https://github.com/dreikanter/rails-ansible-sample.git"
git_branch: master
git_key_file: None

# NOTE: These paths should correspond to puma.rb
app_root_path: "/var/www/{{ app_name }}"
app_path:      "{{ app_root_path }}/current"
shared_path:   "{{ app_root_path }}/shared"
logs_path:     "{{ shared_path }}/log"
pids_path:     "{{ shared_path }}/pids"
sockets_path:  "{{ shared_path }}/sockets"
releases_path: "{{ app_root_path }}/releases"

local_source_path: "~/tmp/repo"
dist_path: "~/tmp"

# These paths should be common for Vagrant and CI
secrets_vault_public_key_path: "/secrets/secrets_vault_key.pub"
secrets_vault_private_key_path: "/secrets/secrets_vault_key"

puma_config_file: "{{ app_path }}/config/puma.rb"
puma_socket: "{{sockets_path}}/puma.sock"
