---
#
# playbook: provision
#

ansible_python_interpreter: "/usr/bin/python3"
secrets_path: "~/src/feeder-ansible-secrets"

# role: bootstrap

app_name: feeder
timezone: UTC
locale: en_US.UTF-8

# See https://github.com/debops/ansible-swapfile
swapfile__size: '{{((ansible_memtotal_mb|int * 2) if (ansible_memtotal_mb|int <= 2048) else "512")}}'
swapfile__priority: '-1'
swapfile__use_dd: False
swapfile__files: [ '/swapfile' ]

# role: deploy-user

deploy_user: deploy
deploy_group: "{{deploy_user}}"
deploy_user_path: "/home/{{deploy_user}}"
authorized_public_keys: [ "{{secrets_path}}/scaleway.pub" ]

# role: ruby

rbenv_version: master
ruby_install_version: 0.9.0
ruby_version: 3.2.2

rbenv_repo: "https://github.com/rbenv/rbenv.git"
rbenv_root_path: "{{deploy_user_path}}/.rbenv"
rubies_path: "{{rbenv_root_path}}/versions"
ruby_path: "{{rubies_path}}/{{ruby_version}}"

push_ruby_binaries: True
local_ruby_path: "~/.rbenv/versions/{{ruby_version}}"

rbenv_bin: "{{rbenv_root_path}}/bin/rbenv"
bundle: "{{rbenv_root_path}}/shims/bundle"

# role: nodejs

nodesource_url: https://deb.nodesource.com/setup_12.x

# role: postgres

postgres_user: "{{app_name}}"
postgres_password: "{{app_name}}"

#
# playbook: deploy
#

git_url: "https://github.com/dreikanter/feeder.git"
git_branch: release
git_key_file: None

deployment_path: "/var/www/feeder"

app_path:      "{{deployment_path}}/current"
logs_path:     "{{deployment_path}}/log"
pids_path:     "{{deployment_path}}/pids"
sockets_path:  "{{deployment_path}}/sockets"
releases_path: "{{deployment_path}}/releases"
repo_path:     "{{deployment_path}}/repo"

# These paths should be common for Vagrant and CI
credentials_master_key_path: "{{secrets_path}}/production.key"

puma_config_file: "{{app_path}}/config/puma.rb"
puma_socket: "{{sockets_path}}/puma.sock"

# role: letsenrypt

letsencrypt_email: alex.musayev@gmail.com
letsencrypt_dir: /var/www/letsencrypt
letsencrypt_domain_name: frf.im
