---
#
# playbook: provision
#

# role: commons

app_name: myapp
timezone: UTC
locale: en_US.UTF-8
swap_enabled: yes
swap_file_path: /swapfile
swap_file_size_kb: 1024

# role:  deploy-user

deploy_user: deploy
deploy_group: "{{ deploy_user }}"
deploy_user_path: "/home/{{ deploy_user }}"
authorized_public_keys: []

# role: ruby

ruby_install_version: 0.6.0
ruby_version: 2.3.3
rubies_path: "~/.rubies"
ruby_path: "{{ rubies_path }}/{{ ruby_version }}"

# role: nodejs

nodesource_url: https://deb.nodesource.com/setup_6.x

#
# playbook: deploy
#

git_url: "https://github.com/dreikanter/rails-ansible-sample.git"
git_branch: master

app_root_path: "/var/www/{{ app_name }}"
app_path:      "{{ app_root_path }}/current"
shared_path:   "{{ app_root_path }}/shared"
logs_path:     "{{ shared_path }}/log"
pids_path:     "{{ shared_path }}/pids"
releases_path: "{{ app_root_path }}/releases"
secrets_path:  "{{ app_root_path }}/secrets"

local_source_path: "~/tmp/ansible-{{ app_name }}"
dist_path: "~/tmp"
bundle: "{{ ruby_path }}/bin/bundle"

# These paths should be common for Vagrant and CI
secrets_vault_public_key_path: "/{{ app_name }}-secrets/secrets_vault_key.pub"
secrets_vault_private_key_path: "/{{ app_name }}-secrets/secrets_vault_key"
