---
- name: clone or update sources
  git:
    repo: "{{ git_url }}"
    dest: "{{ repo_path }}"
    clone: yes
    update: yes
    version: "{{ git_branch }}"
    accept_hostkey: yes
    key_file: "{{ git_key_file }}"

- name: install gems
  args:
    chdir: "{{ repo_path }}"
  environment:
    RAILS_ENV: "{{ rails_env }}"
  shell: "{{ bundle }} install --deployment --without development test"

- name: push configuration key
  copy:
    src: "{{ secrets_vault_private_key_path }}"
    dest: "{{ deploy_user_path }}/secrets_vault_key"
    owner: "{{ deploy_user }}"
    group: "{{ deploy_group }}"
    mode: 0600

- name: decrypt configuration
  args:
    chdir: "{{ repo_path }}"
  shell: "{{ bundle }} exec rails secrets:decrypt"
  environment:
    SECRETS_VAULT_PRIVATE_KEY: "{{ deploy_user_path }}/secrets_vault_key"

- name: migrate db (run once)
  become: yes
  become_user: "{{ deploy_user }}"
  run_once: yes
  args:
    chdir: "{{ repo_path }}"
  environment:
    RAILS_ENV: "{{ rails_env }}"
  shell: "{{ bundle }} exec rails db:migrate --trace"

- name: compile assets
  args:
    chdir: "{{ repo_path }}"
  shell: "{{ bundle }} exec rails assets:precompile"
  environment:
    RAILS_ENV: "{{ rails_env }}"

- name: create directory for the new release
  become: yes
  file:
    state: directory
    path: "{{ new_release_path }}"
    owner: "{{ deploy_user }}"
    group: "{{ deploy_group }}"
    mode: 0755

- name: push distribution
  become: yes
  become_user: "{{ deploy_user }}"
  shell: "rsync -a {{ repo_path }}/ {{ new_release_path }} --exclude .git"

- name: link most recent release to "/var/www/app/current"
  become: yes
  file:
    state: link
    src: "{{ new_release_path }}"
    dest: "{{ app_path }}"
    force: yes
    owner: "{{ deploy_user }}"
    group: "{{ deploy_group }}"
