---
- name: build app distribution
  hosts: localhost
  tasks:

    - name: ensure local source directory is ready
      file:
        path: "{{ local_source_path }}"
        state: directory
        mode: 0755

    - name: clone or update sources
      git:
        repo: "{{ git_url }}"
        dest: "{{ local_source_path }}"
        clone: yes
        update: yes
        version: "{{ git_branch }}"
        accept_hostkey: yes

    - name: bundle install
      bundler:
        chdir: "{{ local_source_path }}"
        executable: "{{ bundle }}"
        deployment_mode: yes
        exclude_groups:
          - development
          - test

    - name: decrypt configuration
      args:
        chdir: "{{ local_source_path }}"
      shell: "{{ bundle }} exec rails secrets:decrypt"
      environment:
        SECRETS_VAULT_PRIVATE_KEY: "{{ secrets_vault_private_key_path }}"

    - name: precompile assets
      args:
        chdir: "{{ local_source_path }}"
      local_action: "shell {{ bundle }} exec rails assets:precompile"
      environment:
        RAILS_ENV: "{{ rails_env }}"

    - name: get distribution path
      set_fact:
        dist_path: "~/tmp/{{ app_name}}-{{ lookup('pipe', 'date -u +%Y%m%d%H%M%S') }}"

    - name: create app distribution
      args:
        chdir: "{{ local_source_path }}"
      shell: "tar --create --exclude=.git --exclude=tmp/* --exclude=log/* -gzip --verbose --file '{{ dist_path }}' ."

    - name: get file distribution size
      stat:
        path: "{{ dist_path }}"
      register: distro

    - debug:
        msg: "Distribution size: {{ distro.stat.size }}"
      when: distro is defined and distro.stat is defined

