---
- hosts: all
  gather_facts: no
  run_once: true
  tasks:
    - set_fact:
        new_release_name: "{{ app_name }}-{{ lookup('pipe', 'date -u +%Y%m%d%H%M%S') }}"
        run_once: yes
    - set_fact:
        new_release_path: "{{ releases_path }}/{{ new_release_name }}"
        run_once: true

- name: build app distribution
  hosts: localhost
  roles:
    - build-distribution

- name: deploy app distribution
  hosts:
    - app
    - work
  roles:
    - deploy-distribution

- name: launch app server
- name: launch workers
