---
- hosts:
    - app
    - worker
    - db
    - redis
    - elasticsearch
  become: yes
  roles:
    - common
    - deploy-user

- hosts: db
  become: yes
  roles:
    - postgres

- hosts: redis
  become: yes
  roles:
    - redis

- hosts: elasticsearch
  become: yes
  roles:
    - elasticsearch

- hosts:
    - app
    - worker
  roles:
    - nodejs
    - ruby

- hosts: app
  roles:
    - nginx
