---
- hosts: all
  become: true
  roles:
    - bootstrap
    - deploy-user
    - postgres
    - redis
    - nodejs
    - ruby
    - nginx

    # should be ran after nginx is installed; configured domain shouls
    # point to the server
    # - letsencrypt

    # - chrome
