---
- hosts:
    - app
    - worker
    - db
  become: yes
  roles:
    - bootstrap
    - common
    - debops.swapfile
    - deploy-user

- hosts: db
  become: yes
  roles:
    - postgres

- hosts:
    - app
    - worker
  roles:
    - nodejs
    - ruby

- hosts: app
  roles:
    - nginx
