---
- name: create directory for the new release
  become: yes
  file:
    state: directory
    path: "{{ new_release_path }}"
    owner: "{{ deploy_user }}"
    group: "{{ deploy_group }}"
    mode: 0755

- name: push distribution
  become: yes
  become_user: "{{ deploy_user }}"
  synchronize:
    src: "{{ local_source_path }}/"
    dest: "{{ new_release_path }}"
    mode: push
    archive: no
    recursive: yes
    rsync_opts:
      - "--exclude=.git"
      - "--exclude=tmp/*"
      - "--exclude=log/*"
      - "--quiet"

- name: update ownership
  become: yes
  file:
    path: "{{ new_release_path }}"
    recurse: yes
    owner: "{{ deploy_user }}"
    group: "{{ deploy_group }}"
    mode: u=rwX,g=rX,o=rX

- name: link most recent release to "/var/www/app/current"
  become: yes
  file:
    state: link
    src: "{{ new_release_path }}"
    dest: "{{ app_path }}"
    force: yes
    owner: "{{ deploy_user }}"
    group: "{{ deploy_group }}"

- name: migrate db (run once)
  become: yes
  become_user: "{{ deploy_user }}"
  run_once: yes
  args:
    chdir: "{{ new_release_path }}"
  environment:
    RAILS_ENV: "{{ rails_env }}"
  shell: "{{ bundle }} exec rails db:migrate --trace"
