---
- name: ensure /etc/apt/keyrings exists
  become: yes
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"

- name: add nodesource gpg key
  become: yes
  ansible.builtin.get_url:
    url: https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key
    dest: /etc/apt/keyrings/nodesource.asc
    mode: "0644"

- name: add nodesource apt repository
  become: yes
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/nodesource.asc] https://deb.nodesource.com/node_{{node_major}}.x nodistro main"
    filename: nodesource
    state: present

- name: install nodejs
  become: yes
  ansible.builtin.apt:
    name: nodejs
    state: present
    update_cache: yes
