---
- name: download setup script
  become: true
  get_url:
    url: "{{nodesource_url}}"
    dest: /tmp/nodesource_setup
    mode: "0666"

- name: add installation source
  become: true
  shell: cat /tmp/nodesource_setup | bash -E -

- name: install nodejs
  become: true
  apt:
    name: nodejs
    state: present
