---
- name: download script to add installation source
  become: yes
  get_url:
    url: "{{ nodesource_url }}"
    dest: /tmp/nodesource_setup
    mode: 0666

- name: add installation source
  become: yes
  shell: cat /tmp/nodesource_setup | bash -E -

- name: install nodejs
  become: yes
  apt:
    name: nodejs
    state: present
