---
- name: "cronjob to update the feeds"
  cron:
    name: "feeds"
    minute: "*/15"
    job: "cd {{app_path}} && RAILS_ENV=production {{bundle}} exec rails feeder:pull_stale"

- name: "cronjob to update subscribers count"
  cron:
    name: "subs"
    minute: "*/30"
    job: "cd {{app_path}} && RAILS_ENV=production {{bundle}} exec rails feeder:subs"

- name: "cronjob to clean the db"
  cron:
    name: "clean"
    minute: "0"
    hour: "0"
    job: "cd {{app_path}} && RAILS_ENV=production {{bundle}} exec rails feeder:clean"
