---
- name: create site configuration
  template:
    src: "nginx-site.conf"
    dest: "/etc/nginx/sites-available/{{ app_name }}"
    owner: root
    group: root

- name: enable site configuration
  file:
    src: "/etc/nginx/sites-available/{{ app_name }}"
    dest: "/etc/nginx/sites-enabled/{{ app_name }}"
    state: link

- name: restart nginx
  service:
    name: nginx
    state: reloaded
