---
- name: ensure directories are ready
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - "{{ local_source_path }}"
    - "{{ dist_path }}"

- set_fact:
    local_bundle: "~/.rbenv/shims/bundle"

- name: clone or update sources
  git:
    repo: "{{ git_url }}"
    dest: "{{ local_source_path }}"
    clone: yes
    update: yes
    version: "{{ git_branch }}"
    accept_hostkey: yes
    key_file: "{{ git_key_file }}"

- name: install gems
  args:
    chdir: "{{ local_source_path }}"
  shell: "{{ local_bundle }} install --deployment --without development test"

- name: decrypt configuration
  args:
    chdir: "{{ local_source_path }}"
  shell: "{{ local_bundle }} exec rails secrets:decrypt"
  environment:
    SECRETS_VAULT_PRIVATE_KEY: "{{ secrets_vault_private_key_path }}"

- name: compile assets
  args:
    chdir: "{{ local_source_path }}"
  shell: "{{ local_bundle }} exec rails assets:precompile"
  environment:
    RAILS_ENV: "{{ rails_env }}"
