---
- name: Create service unit
  become: true
  ansible.builtin.template:
    src: puma.service.j2
    dest: /etc/systemd/system/puma.service

- name: Create service unit
  become: true
  ansible.builtin.template:
    src: puma.socket.j2
    dest: /etc/systemd/system/puma.socket

- name: Enable and start service
  become: true
  ansible.builtin.systemd:
    name: puma
    daemon_reload: true
    state: restarted
    enabled: true

- name: Enable logrotate config for puma
  become: true
  ansible.builtin.template:
    src: logrotate.j2
    dest: /etc/logrotate.d/puma

- name: Ensure nginx site configuration present
  become: true
  ansible.builtin.template:
    src: nginx-site.conf.j2
    dest: /etc/nginx/sites-available/{{app_name}}
    owner: root
    group: root

- name: Ensure nginx site configuration is enabled
  become: true
  ansible.builtin.file:
    src: /etc/nginx/sites-available/{{app_name}}
    dest: /etc/nginx/sites-enabled/{{app_name}}
    state: link

- name: Restart nginx
  become: true
  ansible.builtin.service:
    name: nginx
    state: reloaded
