---
- name: create service unit
  become: yes
  template:
    src: puma.service.j2
    dest: "/etc/systemd/system/puma.service"

- name: create service unit
  become: yes
  template:
    src: puma.socket.j2
    dest: "/etc/systemd/system/puma.socket"

- name: enable and start service
  become: yes
  systemd:
    name: "{{ puma_service_name }}"
    daemon_reload: yes
    state: restarted
    enabled: true

# # TODO: Lookup for http_basic_auth_* env vars
# - name: generate .htpasswd
#   when: (http_basic_auth is defined) and http_basic_auth
#   htpasswd:
#     create: yes
#     state: present
#     name: "{{ http_basic_auth_name }}"
#     password: "{{ http_basic_auth_password }}"
#     path: "{{ app_path }}/config/.htpasswd"

- name: ensure nginx site configuration present
  become: yes
  template:
    src: "nginx-site.conf"
    dest: "/etc/nginx/sites-available/{{ app_name }}"
    owner: root
    group: root

- name: ensure nginx site configuration is enabled
  become: yes
  file:
    src: "/etc/nginx/sites-available/{{ app_name }}"
    dest: "/etc/nginx/sites-enabled/{{ app_name }}"
    state: link

- name: restart nginx
  become: yes
  service:
    name: nginx
    state: reloaded
