---
- name: "install dependencies"
  apt:
    name: software-properties-common
    state: latest
    update_cache: true

- name:
  become: yes
  apt_repository:
    repo: "ppa:canonical-chromium-builds/stage"

- name: "install chromium"
  apt:
    name: chromium-browser
    state: latest
    update_cache: true
