---
- name: "download gpg key"
  become: yes
  apt_key:
    url: https://dl.yarnpkg.com/debian/pubkey.gpg
    state: present

- name: "ensure debian package is in sources list"
  become: yes
  lineinfile:
    create: true
    dest: /etc/apt/sources.list.d/yarn.list
    regexp: "deb https://dl.yarnpkg.com/debian/ stable main"
    line: "deb https://dl.yarnpkg.com/debian/ stable main"
    state: present

- name: "install yarn package"
  become: yes
  become_user: root
  apt:
    update_cache: yes
    name: yarn
    state: present

- name: "fix permissions for local config"
  become: yes
  file:
    path: "{{deploy_user_path}}/.config/yarn"
    state: "directory"
    owner: "{{deploy_user}}"
    group: "{{deploy_group}}"
    mode: 0700
