- name: set locale to
  command: /usr/sbin/update-locale LANG={{locale}} LC_ALL={{locale}}

- name: set local time
  file:
    src: "/usr/share/zoneinfo/{{ timezone }}"
    path: /etc/localtime
    state: link

- name: set timezone
  template:
    src: timezone
    dest: /etc/timezone
  notify: update tzdata
