---
- name: safe upgrade packages
  apt:
    update_cache: yes
    upgrade: safe

- include: swap.yml
  when: swap_enabled is defined and swap_enabled == true

- include: tools.yml

- include: locale.yml

- include: systemd.yml
