---
- name: add oracle java repository
  apt_repository:
    repo: "ppa:webupd8team/java"

- name: accept java licence
  shell: "echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | tee /etc/oracle-java-8-licence-acceptance | /usr/bin/debconf-set-selections"
  args:
    creates: /etc/oracle-java-8-licence-acceptance

- name: add apt repository key
  apt_key:
    url: https://packages.elastic.co/GPG-KEY-elasticsearch

- name: setup elasticsearch repository
  lineinfile:
    dest: /etc/apt/sources.list.d/elasticsearch-2.x.list
    line: "deb http://packages.elastic.co/elasticsearch/{{ elasticsearch_version }}/debian stable main"
    regexp: packages\.elastic\.co\/elasticsearch
    state: present
    create: yes

- name: install apt packages
  apt:
    name: "{{ item }}"
    state: latest
  with_items: "{{ elasticsearch_packages }}"

- name: enable and restart service
  service:
    name: elasticsearch
    state: restarted
    enabled: yes
