---
- name: add apt repository key
  become: yes
  apt_key:
    id: ACCC4CF8
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc

- name: add postgresql official apt repository
  become: yes
  apt_repository:
    repo: "deb http://apt.postgresql.org/pub/repos/apt/ {{ansible_distribution_release}}-pgdg main"

- name: install postgres
  become: yes
  apt:
    name: "{{item}}"
    state: present
    update_cache: yes
  with_items:
    - "libpq-dev"
    - "postgresql-{{postgres_version}}"
    - "postgresql-contrib-{{postgres_version}}"

- name: install psycopg2 for ansible postgresql_user module
  become: true
  apt:
    name: "{{item}}"
    state: latest
  with_items:
    - python3-psycopg2

- name: configure authentication
  become: yes
  template:
    src: "pg_hba.conf"
    dest: "{{postgres_hba_file}}"
    owner: "root"
    group: "root"
    mode: 0644

- name: restart postgres
  become: yes
  service:
    name: postgresql
    state: restarted

- name: create db user
  become: yes
  become_user: "{{postgresql_admin_user}}"
  postgresql_user:
    name: "{{postgres_user}}"
    password: "{{postgres_password}}"
    state: present
    role_attr_flags: "SUPERUSER,CREATEDB,LOGIN"

- set_fact:
    postgres_db_name: "{{app_name}}_production"

- name: create database
  become: yes
  become_user: "{{postgresql_admin_user}}"
  postgresql_db:
    name: "{{postgres_db_name}}"
    state: present
    owner: "{{postgres_user}}"

- name: grant privileges
  become: yes
  become_user: "{{postgresql_admin_user}}"
  postgresql_privs:
    database: "{{postgres_db_name}}"
    state: "present"
    privs: "ALL"
    type: "table"
    objs: "ALL_IN_SCHEMA"
    schema: "public"
    roles: "{{postgres_user}}"
    grant_option: yes

- name: create extensions
  become: yes
  become_user: "{{postgresql_admin_user}}"
  postgresql_ext:
    name: "{{item}}"
    db: "{{postgres_db_name}}"
    state: "present"
  with_items: "{{postgres_extensions}}"
  when: "{{postgres_extensions}}"

- name: install pip3 for for ansible pip module
  become: true
  apt:
    name: "{{item}}"
    state: latest
  with_items:
    - python3-pip

- name: install pgcli
  become: yes
  pip:
    name: pgcli
