---
- name: "install letsencrypt"
  apt:
    name: "letsencrypt"
    state: "latest"

- name: "create letsencrypt directory"
  file:
    name: "{{letsencrypt_dir}}"
    state: "directory"

- name: "install nginx site for letsencrypt requests"
  template:
    src: "templates/nginx-http.j2"
    dest: "/etc/nginx/sites-enabled/http"

- name: "reload nginx to activate letsencrypt site"
  service:
    name: nginx
    state: restarted

- name: "create letsencrypt certificate"
  shell: "certbot certonly --non-interactive --webroot --webroot-path /var/www/letsencrypt --email alex.musayev@gmail.com --agree-tos --domain frf.im"
  args:
    creates: "/etc/letsencrypt/live/{{letsencrypt_domain_name}}"

- name: "generate dhparams"
  shell: "openssl dhparam -out /etc/nginx/dhparams.pem 2048"
  args:
    creates: "/etc/nginx/dhparams.pem"

- name: "add letsencrypt cron job for cert renewal"
  cron:
    name: "letsencrypt_renewal"
    special_time: "weekly"
    job: "certbot certonly --non-interactive --webroot --webroot-path /var/www/letsencrypt --email alex.musayev@gmail.com --agree-tos --domain frf.im && service nginx reload"
