---
- name: install rbenv
  become: yes
  become_user: "{{deploy_user}}"
  git:
    repo: "{{rbenv_repo}}"
    dest: "{{rbenv_root_path}}"
    accept_hostkey: yes
    version: "{{rbenv_version}}"
    clone: yes
    update: yes

- name: update .bashrc
  become: yes
  become_user: "{{deploy_user}}"
  blockinfile:
    path: "{{deploy_user_path}}/.bashrc"
    backup: yes
    # owner: "{{deploy_user}}"
    # group: "{{deploy_group}}"
    block: |
      export PATH="$HOME/.rbenv/bin:$PATH"
      eval "$(rbenv init -)"

  become: yes
  become_user: "{{deploy_user}}"
  blockinfile:
    path: "{{deploy_user_path}}/.gemrc"
    backup: yes
    # owner: "{{deploy_user}}"
    # group: "{{deploy_group}}"
    mode: 0600
    block: |
      :sources:
      - https://rubygems.org
      gem: --no-ri --no-rdoc
