---
- name: install rbenv
  become: true
  become_user: "{{ deploy_user }}"
  ansible.builtin.git:
    repo: "{{ rbenv_repo }}"
    dest: "{{ rbenv_root_path }}"
    accept_hostkey: true
    version: "{{ rbenv_version }}"
    clone: true
    update: true

- name: add rbenv init to .bashrc
  become: true
  become_user: "{{ deploy_user }}"
  ansible.builtin.blockinfile:
    path: "{{ deploy_user_path }}/.bashrc"
    create: true
    backup: true
    block: |
      export PATH="$HOME/.rbenv/bin:$PATH"
      eval "$(rbenv init -)"

- name: create or update .gemrc
  become: true
  become_user: "{{ deploy_user }}"
  ansible.builtin.blockinfile:
    path: "{{ deploy_user_path }}/.gemrc"
    create: true
    backup: true
    mode: "0600"
    block: |
      :sources:
      - https://rubygems.org
      gem: --no-ri --no-rdoc
