---
- name: install rbenv
  become: yes
  become_user: "{{ deploy_user }}"
  git:
    repo: "{{ rbenv_repo }}"
    dest: "{{ rbenv_root_path }}"
    accept_hostkey: yes
    version: "{{ rbenv_version }}"
    clone: yes
    update: yes

- name: add rbenv init to .bashrc
  become: yes
  become_user: "{{ deploy_user }}"
  blockinfile:
    path: "{{ deploy_user_path }}/.bashrc"
    create: true
    backup: yes
    block: |
      export PATH="$HOME/.rbenv/bin:$PATH"
      eval "$(rbenv init -)"

- name: create or update .gemrc
  become: yes
  become_user: "{{ deploy_user }}"
  blockinfile:
    path: "{{ deploy_user_path }}/.gemrc"
    create: true
    backup: yes
    mode: 0600
    block: |
      :sources:
      - https://rubygems.org
      gem: --no-ri --no-rdoc
