---
- name: check if ruby-install is already installed
  become: true
  ansible.builtin.stat:
    path: /usr/local/share/doc/ruby-install-{{ ruby_install_version }}
  register: ruby_install_path

- name: download ruby-install
  become: true
  when: ruby_install_path.stat.exists == false
  ansible.builtin.unarchive:
    src: https://github.com/postmodern/ruby-install/archive/v{{ ruby_install_version }}.tar.gz
    remote_src: true
    dest: "{{ deploy_user_path }}"
    owner: "{{ deploy_user }}"
    group: "{{ deploy_group }}"

- name: install ruby-install
  become: true
  when: ruby_install_path.stat.exists == false
  ansible.builtin.make:
    chdir: "{{ deploy_user_path }}/ruby-install-{{ ruby_install_version }}"
    target: install
